### ISSUE TITLE
Refusi Grammaticali

### ISSUE THREAD

**Issue by Penaz91** [MiPnamic/mipnamic.github.io#1]
**Pagina principale**
This website is about me, my company, my job and whatever comes to my mind. -> This website is about me, my company, my job, and whatever comes to my mind. (Oxford comma)

you can find my last posts -> you can find my latest posts

you may need for get in touch with me. -> you may need to get in touch with me.

Please, notice: This site don’t uses cookies, deal with it… -> Please, notice: This site doesn’t use cookies, deal with it…

**Pagina /Company**

Actually I work with some professionals -> I actually work with some professinals

We work together for better understand our customers needs and release them what they asked for. -> We work together to understand our customers' needs better, and give them what they asked for.

**/about**

 problem-solving addicted ->  problem-solving addict

 I officially become a Developer ->  I officially became a Developer 

**/privacy**

people have find us -> people have found us

This website do not uses Third Party analytics or anything else. -> This website does not use Third Party analytics or anything else.

 it sound stupid but it’s more funnier this way. ->  it sounds stupid but it’s funnier this way.

**Comment by MiPnamic** [comment]
Grazie @Penaz91 per il supporto i testi sono stati corretti nel repo dedicato a questo sito che non è più questo (il sito non è più hosted by Github) nuova url: [https://github.com/MiPnamic/MiPnamic.net](url)
